[faucet] task: reconfigure git
symbol/product pull request #395
Opened 2023-05-22 19:33 UTC by AnthonyLaw

config `.github` and `lint` path.

2023-05-22 19:49 UTC, Jaguar0625 approved these changes

2023-05-22 19:51 UTC, Jaguar0625 requested changes
please update main README

2023-05-22 20:45 UTC, AnthonyLaw commented
> please update main README

I update the readme table and pre-build the URL following the previous link

2023-05-23 01:49 UTC, Wayonb requested changes

2023-05-23 01:49 UTC, Wayonb commented on .github/dependabot.yaml
> +    versioning-strategy: increase
add this ``versioning-strategy`` to backend and authenticator also

2023-05-23 01:49 UTC, Wayonb commented on README.md
> +[faucet-frontend-test]: https://jenkins.symboldev.com/buildStatus/icon?job=Symbol%2Fgenerated%2Fproduct%2Ffaucet-frontend%2Fdev%2F&config=faucet-frontend-test
missing the build section for frontend?

2023-05-23 12:18 UTC, Jaguar0625 reviewed
i missed this first time, but please alphabetize everything

so faucet should appear after explorer, not at end of files

2023-05-23 20:59 UTC, Jaguar0625 commented
> i missed this first time, but please alphabetize everything
> 
> so faucet should appear after explorer, not at end of files

Seems like you still need to reorder in some files - (buildConfiguration, codecov, etc)

2023-05-24 15:05 UTC, Jaguar0625 commented on .github/dependabot.yaml
>      target-branch: dev
alphabetize this file

2023-05-24 15:05 UTC, Jaguar0625 commented on .gitlintmodules
> +optin/puller|optin/reporting|optin/reporting/client|tools/vanity|monorepo|explorer/nodewatch|lightapi/python|faucet/authenticator|faucet/backend|faucet/frontend
please alphabetize

2023-05-24 15:05 UTC, Jaguar0625 commented on README.md
> +| [@faucet/authenticator](faucet/authenticator) | [![lint][faucet-authenticator-lint]][faucet-authenticator-job] | | [![test][faucet-authenticator-test]][faucet-authenticator-job]| [![][faucet-authen
please alphabetize

2023-06-12 11:39 UTC, Jaguar0625 approved these changes

2023-06-12 14:17 UTC, merged