[tools/vanity]: add to build and README
symbol/product pull request #75
Opened 2022-04-22 14:26 UTC by Jaguar0625

2022-04-27 17:11 UTC, Wayonb requested changes

2022-04-27 17:11 UTC, Wayonb commented on .github/buildConfiguration.yaml
> +builds:
There should only be one builds property which have a list of projects.

2022-04-27 19:53 UTC, gimre-xymcity approved these changes

2022-05-05 14:24 UTC, Wayonb approved these changes

2022-05-05 14:51 UTC, merged