[explorer/nodewatch] task: fix nodewatch layout issue
symbol/product pull request #82
Opened 2022-05-09 12:08 UTC by AnthonyLaw

### What was the issue?
- nodewatch should belong to `explorer` folder

### What's the fix?
- move `nodewatch` to `explorer`
- update readme and build config path

2022-05-09 19:14 UTC, Jaguar0625 requested changes
please rebase on top of dev

2022-05-09 23:44 UTC, Jaguar0625 commented on .github/buildConfiguration.yaml
> +    path: explorer/nodewatch
you have duplicate one above

2022-05-09 23:44 UTC, Jaguar0625 commented on .gitlintmodules
> +optin/puller|tools/vanity|monorepo|explorer/nodewatch
@0x6861746366574 do you want `[nodewatch]` or `[explorer/nodewatch]` tag?

2022-05-10 13:09 UTC, Jaguar0625 approved these changes

2022-05-10 13:09 UTC, Jaguar0625 approved these changes
👍

2022-05-25 18:40 UTC, AnthonyLaw commented
@Jaguar0625 I just rebase onto dev

2022-05-25 18:49 UTC, Jaguar0625 approved these changes

2022-05-25 19:23 UTC, merged