[snap]: Added import account feature
symbol/product pull request #980
Opened 2024-06-25 09:41 UTC by AnthonyLaw

## What was the issue?
- The user is not allowed to import private in the wallet.

## What's the fix?
- Added import account logic, allowing the user to provide an account name and private key for import into snap state.
    - Once the private key is imported, MetaMask's confirmation box will pop up, and the user needs to approve it.
    - If the private key is already imported, MetaMask's alert box will pop up.
- Refactor: removed `components/AccountCreateModalBox` and replaced it with `AccountCreationFormModalBox` which can be shared between `Create/Import` forms.
- Installed Symbol-sdk to frontend project.
- Added an `import` label in accounts list.

## Screenshot

![Screenshot 2024-06-25 at 5 20 02 PM](https://github.com/symbol/product/assets/5649156/379b0a8f-e460-499e-8d16-4300dba40623)

![Screenshot 2024-06-25 at 5 19 53 PM](https://github.com/symbol/product/assets/5649156/23ddb191-b3dc-446c-8f6d-ed63b7c512e5)

![image](https://github.com/symbol/product/assets/5649156/d0ee5191-6815-4fee-9b6e-d06b7d3a040f)

![image](https://github.com/symbol/product/assets/5649156/2c4b1f76-a3c6-4355-a2dc-3dcfb97a24da)

2024-06-25 16:18 UTC, Wayonb approved these changes
👍🏾

2024-06-26 07:49 UTC, AnthonyLaw commented on snap/backend/src/utils/accountUtils.js
> +			const existingAccount = Object.values(accounts).find(account => account.privateKey === keyPair.privateKey.toString());
I made update.

2024-06-28 05:04 UTC, Wayonb requested changes

2024-06-28 17:56 UTC, AnthonyLaw commented on snap/backend/src/utils/accountUtils.js
> +		state, facade, keyPair, accountLabel, type, addressIndex = null
oh yeah, thanks for remind 👍🏼

2024-06-28 17:58 UTC, AnthonyLaw commented on snap/backend/src/utils/accountUtils.js
> +	IMPORTED: 'import'
import: The account is generated from the private key given by the user.
metamask: The account is generated from bip44 and derives the private key from metamask.

2024-07-02 03:25 UTC, Wayonb approved these changes
👍🏾

2024-07-02 08:20 UTC, merged